import streamlit as st

st.title("About")
st.write('''
        This dashboard was created to visualize data generated by the interactive collective behavior showcase tank at Humboldt Forum Berlin.       
        ''')
st.write('''
        Together with the streamlit source code there is also a jupyter notebook version in this github repository: https://github.com/jotpio/thesis 
        ''')
st.caption("2022 - Developed by Jonas Piotrowski")