import streamlit as st

st.title("About")
st.write('''
        This dashboard was created to visualize data generated by the interactive collective behavior showcase tank at Humboldt Forum Berlin.
        There is also a jupyter notebook version at 
        
        ''')
st.caption("2022 - Developed by Jonas Piotrowski")