import streamlit as st
import io
from deta import Deta  # Import Deta



from template.page import Page

class AboutPage(Page):
    
    def __init__(self, data_model):
        super().__init__(data_model)
        self.deta_image_drive = None
        self.setup_deta_image_drive()
    
    def run_page(self, title, description):
        super().run_page(title, description)
        
        #
        #PAGE
        #
        col1, col2 = st.columns([3,1])
        with col1:
            st.write(""" 
                    This is the exhibit all the data stems from. visitors can use the touchscreen to control a small two-wheeled robot 
                    to interact with simulated fish wich are projeted onto the opaque tank floor. 
                    """)
            st.write(""" 
                    You can find out more about the data structure on the Data Structure page in the left sidebar.
                    """)
            st.write("The exhibit was developed by David James of IGB and Jonas Piotrowski of ScioI under the supervision of Dr. David Bierbach ")
        with col2:
            # show rack image
            rack_image_stream = self.deta_image_drive.get("rack1.jpg")
            with io.BytesIO() as in_mem_rack_image:
                for chunk in rack_image_stream.iter_chunks(4096):
                    in_mem_rack_image.write(chunk)
                rack_image_stream.close()
                st.image(in_mem_rack_image, caption="The rack at Humboldt Forum", width=350, use_column_width='auto')
        
        st.write('''
                In addition to the streamlit source code there is also a jupyter notebook version in this github repository: https://github.com/jotpio/thesis 
                ''')
        st.caption("2022 - Developed by Jonas Piotrowski")


    def setup_deta_image_drive(self):
        deta = Deta(st.secrets["deta_key"])        # Initialize with a Project Key
        self.deta_image_drive = deta.Drive("images_HF")

if __name__ == "__main__":
    st.set_page_config(
        page_title="About",
        page_icon="❓",
        layout="wide",
    )  
    if 'data_model' not in st.session_state or not st.session_state['data_model'].dates_dict:
        st.warning("Data not loaded! Go to Home to load data.", icon="⚠️")
    else:
        page = AboutPage(st.session_state['data_model'])
        title = "About"
        description =   """
                        This dashboard was created to visualize data generated by the interactive collective behavior showcase tank at Humboldt Forum Berlin.
                        """
        page.run_page(title, description)